require('dotenv').config();
const admin = require('firebase-admin');

const serviceAccount = require('./google-credentials.json');
if (!admin.apps.length) admin.initializeApp({ credential: admin.credential.cert(serviceAccount) });
const db = admin.firestore();

async function cleanupBypassAnomalies() {
    console.log(`[Database Cleanup] 🧹 Hunting down 0.00 EUR anomalies generated by the text-parser bypass...`);
    
    // We target only records starting with Auto- and amount === 0 to be perfectly safe
    const snapshot = await db.collection('invoices')
        .where('amount', '==', 0)
        .get();
        
    let deletedCount = 0;
    const batch = db.batch();
    
    snapshot.forEach(doc => {
        const data = doc.data();
        if (data.invoiceId && data.invoiceId.toString().startsWith('Auto-')) {
            console.log(`   -> 🗑️ Deleting Junk Record: ${data.vendorName} | ${data.invoiceId}`);
            batch.delete(doc.ref);
            deletedCount++;
        }
    });
    
    if (deletedCount > 0) {
        await batch.commit();
        console.log(`[Database Cleanup] ✅ Successfully purged ${deletedCount} garbage records.`);
    } else {
        console.log(`[Database Cleanup] 🧼 No junk records found.`);
    }
    
    process.exit(0);
}

cleanupBypassAnomalies();
