const admin = require('firebase-admin');
const serviceAccount = require('./google-credentials.json');

if (!admin.apps.length) {
    admin.initializeApp({
        credential: admin.credential.cert(serviceAccount)
    });
}
const db = admin.firestore();

async function deleteNunnerDuplicates() {
    console.log('Deleting NUNNER duplicates generated by the restore script...');

    // IDs identified in our previous diagnostic check that have bad invoiceIds (dates/titles instead of numbers)
    // created during the latest ingestion run.
    const badDocs = ['B9ZRPbss57zUbaKXEBPn', 'ePkBpJ9Pz9txV2f9pbGT'];

    const batch = db.batch();
    for (const docId of badDocs) {
        const docRef = db.collection('invoices').doc(docId);
        batch.delete(docRef);
        console.log(`Queued doc for deletion: ${docId}`);
    }

    await batch.commit();
    console.log(`Successfully deleted ${badDocs.length} duplicate NUNNER invoices.`);
    process.exit(0);
}

deleteNunnerDuplicates();
