require('dotenv').config();
const { db } = require('./core/firebase.cjs');

async function runSupervisor() {
    console.log(`[Supervisor Agent] 🦅 Launching Supreme Oversight Sweep...`);
    console.log(`[Supervisor Agent] Bypassing Orchestrator memory cache to verify persistent database state...`);

    let anomalyCount = 0;
    
    try {
        const snapshot = await db.collection('invoices').get();
        console.log(`[Supervisor Agent] 📋 Analyzing ${snapshot.docs.length} core financial records...\n`);

        for (const doc of snapshot.docs) {
            const data = doc.data();
            let badRecord = false;
            let strikeReason = '';

            // Rule 1: Absolute Zero Check
            if (data.amount === 0 || data.amount === null || isNaN(data.amount)) {
                badRecord = true;
                strikeReason = `FATAL: Value extracted as ${data.amount} EUR (Zero-value anomaly)`;
            }

            // Rule 2: Signature Mimicry Check
            if (data.vendorName && data.vendorName.toUpperCase() === 'TONGER' && data.amount === 0) {
                badRecord = true;
                strikeReason = `FATAL: Impersonation signature bypass ('TONGER' zero-value)`;
            }

            // Execute the strike
            if (badRecord) {
                console.log(`[Supervisor Agent] 🚨 ANOMALY STRIKE on ID: ${doc.id}`);
                console.log(`   -> Vendor: ${data.vendorName}`);
                console.log(`   -> Internal Ref: ${data.invoiceId}`);
                console.log(`   -> Reason: ${strikeReason}`);

                // Rule 31 safety: never delete a record that has a file attached.
                // A zero-amount record with a file attached means the PDF exists but AI
                // failed to extract the amount — that needs manual review, not deletion.
                if (data.fileUrl) {
                    console.log(`[Supervisor Agent] ⚠️  STRIKE BLOCKED: Record has an attached file (Rule 31). Marking for manual review instead of deleting.`);
                    await doc.ref.update({
                        status: 'NEEDS_REVIEW',
                        validationWarnings: [...(data.validationWarnings || []), `SUPERVISOR: Zero-amount anomaly flagged but file present — manual review required (${strikeReason})`]
                    });
                } else {
                    await doc.ref.delete();
                    console.log(`[Supervisor Agent] 💥 Action Taken: Record forcefully eradicated from Dashboard.\n`);
                    anomalyCount++;
                }
            }
        }

        if (anomalyCount === 0) {
            console.log(`[Supervisor Agent] 🛡️ All systems green. No orchestrator bypasses detected.`);
        } else {
            console.log(`[Supervisor Agent] 🏁 Supervisor sweep complete. Cleaned ${anomalyCount} rogue UI entries generated by the Orchestrator.`);
        }

    } catch (err) {
        console.error(`[Supervisor Agent] System Error:`, err);
    } finally {
        process.exit(0);
    }
}

runSupervisor();
