require('dotenv').config();
const admin = require('firebase-admin');

const serviceAccount = require('./google-credentials.json');
if (!admin.apps.length) admin.initializeApp({ credential: admin.credential.cert(serviceAccount) });
const db = admin.firestore();

async function runSupervisor() {
    console.log(`[Supervisor Agent] 🦅 Launching Supreme Oversight Sweep...`);
    console.log(`[Supervisor Agent] Bypassing Orchestrator memory cache to verify persistent database state...`);

    let anomalyCount = 0;
    
    try {
        const snapshot = await db.collection('invoices').get();
        console.log(`[Supervisor Agent] 📋 Analyzing ${snapshot.docs.length} core financial records...\n`);

        for (const doc of snapshot.docs) {
            const data = doc.data();
            let badRecord = false;
            let strikeReason = '';

            // Rule 1: Absolute Zero Check
            if (data.amount === 0 || data.amount === null || isNaN(data.amount)) {
                badRecord = true;
                strikeReason = `FATAL: Value extracted as ${data.amount} EUR (Zero-value anomaly)`;
            }

            // Rule 2: Signature Mimicry Check
            if (data.vendorName && data.vendorName.toUpperCase() === 'TONGER' && data.amount === 0) {
                badRecord = true;
                strikeReason = `FATAL: Impersonation signature bypass ('TONGER' zero-value)`;
            }

            // Execute the strike
            if (badRecord) {
                console.log(`[Supervisor Agent] 🚨 ANOMALY STRIKE on ID: ${doc.id}`);
                console.log(`   -> Vendor: ${data.vendorName}`);
                console.log(`   -> Internal Ref: ${data.invoiceId}`);
                console.log(`   -> Reason: ${strikeReason}`);
                
                await doc.ref.delete();
                console.log(`[Supervisor Agent] 💥 Action Taken: Record forcefully eradicated from Dashboard.\n`);
                anomalyCount++;
            }
        }

        if (anomalyCount === 0) {
            console.log(`[Supervisor Agent] 🛡️ All systems green. No orchestrator bypasses detected.`);
        } else {
            console.log(`[Supervisor Agent] 🏁 Supervisor sweep complete. Cleaned ${anomalyCount} rogue UI entries generated by the Orchestrator.`);
        }

    } catch (err) {
        console.error(`[Supervisor Agent] System Error:`, err);
    } finally {
        process.exit(0);
    }
}

runSupervisor();
